language: ruby

rvm:
 - 3.0

dist: xenial
os: linux

branches:
  only:
   - master

jobs:
  include:
    - stage: build gem
      script:
       - bundle exec rspec spec
       - bundle exec rake build
    - stage: publish gem
      if: tag =~ /^\d\.\d\.\d(?:-\S*)?$/
      script:
       - gem push -k $RUBYGEMS_APIKEY pkg/*.gem