language: ruby

rvm:
 - 2.5

dist: xenial
os: linux

branches:
  only:
   - master
   - /^\d\.\d\.\d(?:-\S*)?$/

jobs:
  include:
    - stage: build gem
      script:
       - bundle exec rspec spec
       - bundle exec rake build
    - stage: publish gem
      if: branch =~ /^\d\.\d\.\d(?:-\S*)?$/
      script:
       - bundle exec rake build
       - gem push -k $RUBYGEMS_APIKEY pkg/*.gem
